### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by egorsmkv** [JetBrains/la-clojure#95]
```
Plugin 'org.intellij.clojure' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: clojure/lang/Associative
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:412)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: clojure.lang.Associative PluginClassLoader[org.intellij.clojure, 0.7.83]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more
```

IDEA 2016.1

**Comment by vulbecula** [comment]
I also have this issue with latest community edition,

**Comment by egorsmkv** [comment]
@ilyas @Alefas @ilyasergey @OsipovStas PING

**Comment by gangmax** [comment]
I use the following workaround to fix this issue:

1. Download the "Clojure 1.8.0" zip package from "[here](http://clojure.org/community/downloads)";

2. Extract the "clojure-1.8.0.jar" file from the zip package, copy it into your Intellij IDEA installation's sub directory"lib";

3. Install the "La Clojure" plugin again and restart IntelliJ IDEA. This time the plugin works as expected.

My environment: "Ubuntu Xenial" + "IntelliJ IDEA Community 2016.2"

**Comment by egorsmkv** [comment]
In version 2016.2 is not found errors.

**Comment by rimlin** [comment]
Same error, Windows 10, IDEA Community Edition 2016.2.3.
If i install La Clojure from JetBrains store, IDEA silent started and La Clojure not exists on the list of plugins, but if install from the disk, IDEA started with error: 
```
Plugin 'org.intellij.clojure' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.
java.lang.NoClassDefFoundError: clojure/lang/Associative
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:385)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: clojure.lang.Associative
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:214)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more

```
